### PR TITLE
Fix: failing scaling operation in case of multiple VDUs

### LINKED ISSUE #92: Scaling without specifying the VDU may fail for a VNFR with multiple VDUs
When triggering a scaling operation without specifying which VDU to scale, the NFVO chooses one and tries the scaling operation.
In the case of a VNFR with multiple VDUs the NFVO may choose one that has already reached its minimum or maximum number of VNFC instances and returns an error saying that the scaling operation is not possible.
The NFVO does not check if the scaling operation might be possible on another VDU.

### PR DESCRIPTION
**Pull request by ThomasBri**
This closes #92

### CODE REVIEW

File: core/core-impl/src/main/java/org/openbaton/nfvo/core/api/NetworkServiceRecordManagement.java [hunk 1]
```diff
@@ -478,17 +473,27 @@ public void addVNFCInstance(String id, String idVnf, VNFComponent component, Str
...
     }
 
-    if (virtualDeploymentUnit.getScale_in_out()
-        == virtualDeploymentUnit.getVnfc_instance().size()) {
-      throw new WrongStatusException(
-          "The VirtualDeploymentUnit chosen has reached the maximum number of VNFCInstance");
+    if (vdusFound.size() == 0) throw new NotFoundException("No VirtualDeploymentUnit found");
+
+    for (VirtualDeploymentUnit vdu : vdusFound) {
+      if (vdu.getScale_in_out() == vdu.getVnfc_instance().size()) continue;
```
Comment (mpauls) [inline core/core-impl/src/main/java/org/openbaton/nfvo/core/api/NetworkServiceRecordManagement.java]: What happens if vdu.getVnfc_instance().size() is less than vdu.getScale_in_out()? Should also be scalable in this case, shouldn't it?

File: core/core-impl/src/main/java/org/openbaton/nfvo/core/api/NetworkServiceRecordManagement.java [hunk 2]
```diff
@@ -478,17 +473,27 @@ public void addVNFCInstance(String id, String idVnf, VNFComponent component, Str
...
+      virtualDeploymentUnit = vdu;
+      break;
     }
+    if (virtualDeploymentUnit == null)
+      throw new WrongStatusException(
```
Comment (mpauls) [inline core/core-impl/src/main/java/org/openbaton/nfvo/core/api/NetworkServiceRecordManagement.java]: Would throw an NotFoundException so claiming that no VDU was found which allows scale out or is there any problem with an interface which must be changed?

File: core/core-impl/src/main/java/org/openbaton/nfvo/core/api/NetworkServiceRecordManagement.java (hunk 1 above)
Comment (ThomasBri) [inline core/core-impl/src/main/java/org/openbaton/nfvo/core/api/NetworkServiceRecordManagement.java]: The if clause in combination with the continue statement actually filters out all the VDUs which have already reached the maximum number of instances.
